/** THIS FILE IS AUTOGENERATED, DO NOT MODIFY
 * UPDATE THIS FILE BY RUNNING yarn update-blog-list */

import { meta as blogPostOneMeta } from "~/routes/blog/blog-post-one";
import { meta as blogPostThreeMeta } from "~/routes/blog/blog-post-three";
import { meta as blogPostTwoMeta } from "~/routes/blog/blog-post-two";

const blogPostOne = { ...blogPostOneMeta, slug: "blog-post-one" };
export { blogPostOne };

const blogPostThree = { ...blogPostThreeMeta, slug: "blog-post-three" };
export { blogPostThree };

const blogPostTwo = { ...blogPostTwoMeta, slug: "blog-post-two" };
export { blogPostTwo };
